int a = 1;
int b = 2;
int c = 6;
int d = 8;
int e = 3;
int maximum = a;
if (b > maximum) maximum = b;
if (c > maximum) maximum = c;
if (d > maximum) maximum = d;
if (e > maximum) maximum = e;
Console.Write("Maximum is:");
Console.WriteLine(maximum);
